backend:
  name: git-gateway
  repo: Discovery-Data-Lab/blog # Your GitHub repository
  branch: main # Branch to push changes
  base_url: https://ddlgateway.netlify.app/

media_folder: "static/img" # Folder to store uploaded media files
public_folder: "/img" # Path to access media in the public folder

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Banner Image", name: "banner", widget: "image" }
      - { label: "Authors", name: "authors", widget: "list", default: [] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "testimonials" # Name of the collection
    label: "Testimonials" # Label in the CMS
    folder: "data/testimonials" # Folder where entries are stored
    create: true
    slug: "{{slug}}" # Entry slug generation based on name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Text", name: "text", widget: "text" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - { label: "LinkedIn Link", name: "linkedin_link", widget: "string" }
      - { label: "GitHub Link", name: "github_link", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - {
          label: "Personal Site Link",
          name: "personalSite_link",
          widget: "string",
        }
