name: Deploy Hugo Site to FTP Server

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3'  # Use the specific Hugo version

    - name: Build Hugo site
      run: hugo

    - name: Install lftp
      run: sudo apt-get install -y lftp  # Install lftp before using it

    - name: Deploy via FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSW: ${{ secrets.FTP_PASSW }}
      run: |
        lftp -u "$FTP_USER","$FTP_PASSW" "$FTP_SERVER" <<EOF
        set ssl:verify-certificate no
        mirror --reverse --delete --verbose --only-newer ./public_html/ /public_html/
        bye
        EOF
